create database customer_behavior;
use customer_behavior;
show tables;

select * from customer_behavior ;

-- Data Analysis in SQL

-- What is the revenue generated by male vs female customers? 
select gender, SUM(purchase_amount) as revenue from customer_behavior group by gender;
 
-- Which customers used a discount but still spent more than the average purchase amount ?
select customer_id, purchase_amount
from customer_behavior
where discount_applied = 'Yes' and purchase_amount > (select avg(purchase_amount) from customer_behavior) ;

-- Which are the Products with highest average review rating ?

select item_purchased, round(avg(review_rating),2) as avg_review_rating 
from customer_behavior 
group by item_purchased 
order by avg_review_rating desc 
limit 5;

-- Compare average purchase amount between standarad and Express shipping ?

select shipping_type, avg(purchase_amount) 
from customer_behavior 
where shipping_type in ('Standard', 'Express') 
group by shipping_type;


-- Do subscribers spend more ? Compare average spend and total revenue between subscribers and non-subscribers ?

select subscription_status, count(customer_id) as total_customers, round(avg(purchase_amount),2) as avg_spend, round(sum(purchase_amount)) as total_revenue
from customer_behavior
group by subscription_status
order by total_revenue, avg_spend desc;

-- Which 5 Products have the highest percentage of purchases with discounts applied ? this will help us know which are relying on discounts (dividing count of particular product when discounts applied with total count of that particular product * 100) 
select item_purchased, round(100*sum(case when discount_applied = 'YES' then 1 else 0 end)/count(*), 2) as percentage_of_purchases_discounted
from customer_behavior
group by item_purchased
order by percentage_of_purchases_discounted desc 
limit 5;


-- Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the amount count of each segment 

with customer_type as (
select customer_id, previous_purchases,
case when previous_purchases = 1 then 'New'
when previous_purchases between 2 and 10 then 'Returning' 
else 'Loyal'
end as customer_segment
from customer_behavior
)
select customer_segment, count(customer_id) as Number_of_customers
from customer_type 
group by customer_segment
order by Number_of_customers desc;

-- What are the top 3 most purchased products within each category?

with item_count as(
select category, item_purchased, count(customer_id) as total_orders,
row_number() over (partition by category
order by count(customer_id) desc ) as item_rank
from customer_behavior
group by category, item_purchased
)
select item_rank, category, item_purchased, total_orders
from item_count
where item_rank <= 3;


-- Are customers who are repeat buyers (more than 5 previous purchases ) are likely to subscribe ?

select subscription_status, count(customer_id) as repeat_buyers 
from customer_behavior
where previous_purchases >5
group by subscription_status ;


-- What is revenue contribution of each age group ?

select age_group, sum(purchase_amount) as total_revenue
from customer_behavior
group by age_group
order by total_revenue desc;

